### ISSUE TITLE
[RTX 3060] RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by OwenTruong** [turboderp-org/exllamav3#16]
### Summary
- Running `convert.py` results in a `RuntimeError: CUDA error: invalid configuration argument` on my 3060.

### Steps
- Installation
```
git clone https://github.com/turboderp-org/exllamav3.git
cd exllamav3
python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
pip install .
```
- Next, `convert.py`
```
python ./convert.py \
	-i /mnt/data/@/general/llm/quantization/src/shisa-ai/shisa-v2-unphi4-14b \
	-o /mnt/sda4/cache/exl3 \
	-w /mnt/data/@/general/llm/quantization/exl3/models/shisa-ai/shisa-v2-unphi4-14b/5.0 \
	-b 5.0
```
  - Error happened.

### Systems/Environment
- Version: Commit #addeaaaaa76f5d9f9fc28d7d3b9125244235173d
- OS: Ubuntu 22.04.5 LTS
- Python: 3.10.12
- Pip: 22.0.2
- Pytorch Verison: 2.6.0+cu124
- NVCC: Build cuda_12.8.r12.8/compiler.35583870_0
- CUDA: 12.8
- Driver: 570.124.06
- GPU: Nvidia 3060 12GB
- LLM Model: shisa-ai/shisa-v2-unphi4-14b (base model is phi-4)
  - Link: https://huggingface.co/shisa-ai/shisa-v2-unphi4-14b

### CLI Output
```
 -- Creating new job
    Input directory: /mnt/data/@/general/llm/quantization/src/shisa-ai/shisa-v2-unphi4-14b
    Working directory: /mnt/sda4/cache/exl3
    Output directory: /mnt/data/@/general/llm/quantization/exl3/models/shisa-ai/shisa-v2-unphi4-14b/5.0
    Calibration size: 100 rows, 2048 columns
    Target bitrate: 5.0 (decoder), 6 (head)
 -- Loaded model config
    Architecture: LlamaForCausalLM
 -- Created model instance:
     - LlamaModel
         - Embedding
         - [40x] TransformerBlock
             - RMSNorm
             - Attention
                 - [4x] Linear
             - RMSNorm
             - GatedMLP
                 - [3x] Linear
         - RMSNorm
         - Linear
 -- Loaded tokenizer
    Vocab size: 100352
 -- Preparing input state
 -- Loading unquantized module: model.embed_tokens
 -- Quantized: model.embed_tokens                                       bpw: 16.00        rfn: 0.000000  [12.12 s]
 -- Loading unquantized module: model.layers.0
Traceback (most recent call last):
  File "/mnt/data/@/services/exllamav3/./convert.py", line 11, in <module>
    main(_in_args, _job_state)
  File "/mnt/data/@/services/exllamav3/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/@/services/exllamav3/exllamav3/conversion/convert_model.py", line 279, in main
    rs = module.forward(rs, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/transformer.py", line 59, in forward
    y = self.attn.forward(y, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/attn.py", line 235, in forward
    x = self.decode_flash_attn_nc(x, bsz, seqlen, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/attn.py", line 303, in decode_flash_attn_nc
    q, k, v = self.project_qkv(x, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/attn.py", line 243, in project_qkv
    q = self.q_proj.forward(x, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/linear.py", line 249, in forward
    self.capture_H(x, params)
  File "/mnt/data/@/services/exllamav3/exllamav3/modules/linear.py", line 231, in capture_H
    params["capture"][self.qmap]["H"].addmm_(x.T, x)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by OwenTruong** [comment]
I am not sure if it would help, but I added print statement to the below in `/exllamav3/modules/linear.py`
```python
        if params["capture"][self.qmap]["first_key"] == self.key:
            rows = np.prod(x.shape[:-1])
            dim = x.shape[-1]
            x = x.view((rows, dim)).to(torch.float, copy = True)
            print(f'Shape: {x.shape}')
            print(f'Params: {params}')

            params["capture"][self.qmap]["H"].addmm_(x.T, x)
            params["capture"][self.qmap]["count"] += rows
```

It was a bit long so I copied the output to here: https://pastebin.com/ntmUytvK

**Comment by OwenTruong** [comment]
Interesting, it seems like unsloth/phi-4 with the same architecture, `LlamaForCausalLM`, was able to run layer 0 fine. I'll leave it running over night and see what happens.

**Comment by OwenTruong** [comment]
Quantizing `unsloth/phi-4` seemed to have [worked](https://huggingface.co/owentruong/phi-4-EXL3).

I am not sure why, but for some reason, the finetune version, `shisa-ai/shisa-v2-unphi4-14b`, doesn't work. Tried running another finetune version, `LightningRodLabs/Flashlight-v1.0`, and it seem to be able to run layer 0.

**Comment by turboderp** [comment]
The problem seems to be the tokenizer for the finetuned model. If you look in `tokenizer.json`, at the top of the file someone has added this:

```json
  "truncation": {
    "direction": "Right",
    "max_length": 4096,
    "strategy": "LongestFirst",
    "stride": 0
  },
```

I'm not sure what the purpose of that is, as it prevents the `tokenizers` library from tokenizing more than 4096 tokens, and the EXL3 quantizer needs much more than that. I suspect it's unintentionally left over from the finetuning process. But I'll make a note to check for it since apparently it's a thing that can happen, and the quantizer should notice rather than giving a cryptic CUDA error down the line.

In the meantime, quantization should work if you replace it with:

```json
  "truncation": null,
```

Or alternatively just copy `tokenizer.json` over from Phi-4, since they seem to be identical otherwise.

**Comment by turboderp** [comment]
Okay, turns out you can just override that feature when loading the tokenizer. Problem solved.
