### ISSUE TITLE
Convert.py on Qwen3.5 35B gives CUDA erro

### ISSUE THREAD

**Issue by niceblue88** [turboderp-org/exllamav3#169]
Tried to quantise with: python convert.py -i ../Qwen3.5-35B-A3B -o qwen35_35b_exl3_55 -w working -b 5.5

I presume this should work fine, as turboderp has published 5bpw and 6bpw. I have successfully quantised quite a few other models using this same system.

convert.py starts working and seems to be fine for a while, and then crashes consistently as follows:

 -- Resuming at: model.language_model.layers.1
 -- Loading unquantized module: model.language_model.layers.1
 -- Captured: model.language_model.layers.1
Traceback (most recent call last):
  File "/mnt/pool16t/models/exllamav3/convert.py", line 11, in <module>
    main(_in_args, _job_state)
  File "/home/cl/data/exllamav3/exl3q/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pool16t/models/exllamav3/exllamav3/conversion/convert_model.py", line 538, in main
    proxy_err = linear.convert_exl3(
                ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pool16t/models/exllamav3/exllamav3/modules/linear.py", line 326, in convert_exl3
    weight_q, proxy_err, out_tensors = quantize_exl3(
                                       ^^^^^^^^^^^^^^
  File "/mnt/pool16t/models/exllamav3/exllamav3/modules/quant/exl3_lib/quantize.py", line 956, in quantize_exl3
    apply_out_scales, weight_r, g_scale, su, sv = regularize(
                                                  ^^^^^^^^^^^
  File "/mnt/pool16t/models/exllamav3/exllamav3/modules/quant/exl3_lib/quantize.py", line 846, in regularize
    g_scale, mse_scale = g_scale_gss(weight, False, quant_args, pb = pb)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pool16t/models/exllamav3/exllamav3/modules/quant/exl3_lib/quantize.py", line 691, in g_scale_gss
    if f1 < f2:
       ^^^^^^^
torch.AcceleratorError: CUDA error: an illegal memory access was encountered
Search for `cudaErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by rcouture27** [comment]
I've seen this error before when trying -b 4.5. It's the .5 that can cause this. Not sure if it's a bug or just doesn't work well with some models, but I got past this by picking an integer and not a decimal. (just do `-b 5` or `-b 6`)

**Comment by turboderp** [comment]
Well, it turns out it was very stupid. It undershoots the target bitrate when quantizing the first layer, achieving about 3.33bpw when targeting 3.5. This is normal. But because the sparse layers in recent MoE models are so large, that creates a huge surplus in the bits budget which it tries to compensate for in subsequent layers. But there are *too many bits*, so the next attn layer works out to 11 bpw. And of course the code never clamps that value or anything, so it just crashes. 🤦 

It's fixed in the dev branch now, but I'm going to rework the whole scheme anyway one of the coming days, since it was never really designed for MoE models. And the way it mixes bitrates within each layer costs a little bit of performance too on the new fused MoE kernel.

@Ednaordinary The convert->measure->optimize pipeline isn't well documented yet. Basically, you create two base, integer bitrates as you normally would. Say 2bpw and 3bpw. Then you run the measurement:

```
python util/measure.py \
    -i /path/to/2bpw /path/to/3bpw \
    -r /path/to/unquantized_model \
    -o measurement.json
```

This runs a giant, forked batch through the model, testing the effect on KL-divergence from replacing each optimization target in the 2bpw model with the corresponding one from the 3bpw model and ranking all the options for use by the optimizer later. (Target here means module, or submodule group depending on the optimization level, `-l`, but the default level is heavily recommended.) 

Then you can create an optimized model with:

```
python util/optimize.py \
    -i /path/to/2bpw /path/to/3bpw \
    -o /path/to/2.25bpw \
    -b 2.25 \
    -m measurement.json
```

Note that the same rankings would generally also apply at other bitrates, so you could use the same measurement file to also make a 3.14bpw model from 3bpw and 4bpw models.

Especially for models like Qwen3.5 it's advisable to *also* use the recompile script to copy over all `*.linear_attn.*`, `*.self_attn.*` and `*.shared_expert.*` tensors from an even higher bitrate model. In fact that step, which is fairly quick, usually makes a much bigger difference than optimizing the whole model, and it's more cost-effective too (though nothing stops you from doing both, of course.) To use the recompile script, first create an overrides file like so:

```yaml
sources:
  - id: 5
    model_dir: /path/to/5bpw
overrides:
  - key: "*.self_attn.*"
    source: 5
  - key: "*.linear_attn.*"
    source: 5
  - key: "*.shared_expert.*"
    source: 5
```

(You can add more source models and get creative with the key globs too if you want.) 

Then run:

```
python util/recompile.py \
    -i /path/to/3.25bpw \
    -o /path/to/3.25bpw_with_extra_5bpw_layers \
    -or override_file.yaml
```

I do intend to streamline that whole process at some point. In the meantime you could also check out [this project](https://github.com/UnstableLlama/ezexl3/). Haven't had time to try it out myself yet, but it looks very neat.

**Comment by turboderp** [comment]
`dev` branch now has the reworked allocation stuff. It doesn't make measure/optimize completely redundant, but it does use reasonable default priorities for noninteger bitrates.

There's also a `--hq` flag now that increases the bitrate of select layers like shared experts and attn layers in MoE models by two during the initial quant.
