### ISSUE TITLE
[BUG] Autosplit overpacks VRAM by discarding KV Cache placeholders per-layer

### ISSUE THREAD

**Issue by Danielcurly** [turboderp-org/exllamav3#187]
### Description
In high-context scenarios (e.g., 262k context size), the KV Cache overhead becomes a significant portion of the total VRAM usage (~1.1 GB per GPU in an 8-GPU cluster). The current `_load_autosplit` implementation in `Model_LSMixin` (within `model_ls.py`) fails to account for the cumulative weight of these placeholders, leading to `OutOfMemoryError` during or immediately after model loading on multi-GPU setups.

### Root Cause
The loop responsible for testing layer placement resets the cache overhead list for every single module:

```python
# exllamav3/model/model_ls.py:118
qcache_overhead = [] # Discards previous layers' placeholders
for cm in module.all_cache_modules():
    for cl in cm.cache_layers:
        qcache_overhead.append(cl.get_kv_alloc_placeholder())
...
qcache_overhead = None # Dereferences current layer overhead
```

Because `qcache_overhead` is cleared after each layer, the `autosplit` algorithm only "sees" the memory required for the *current* layer's weights and the *current* layer's cache. It "forgets" that the previous layers already packed onto the same device also require their respective KV Cache slots.

### Fix
Maintain a cumulative list of placeholders per device that only resets when transitioning to a new GPU. This forces the allocator to respect the combined footprint of both model weights and the full KV cache placeholder for all layers assigned to that device.

### Proposed Code Change
```diff
--- model_ls.py
+++ mmodel_ls.py
@@ -64,6 +64,7 @@
         dummy_state = None
         prev_load_device = None
         touched_devices = []
+        current_device_cache_overhead = []
         params = self.default_load_params(max_chunk_size)
 
         with ProgressBar(f"Loading (LS)" if progressbar else None, len(modules)) as progress:
@@ -91,6 +92,7 @@
                         # Set VRAM limit if new device
                         if load_device != torch.device("cpu") and load_device != prev_load_device:
                             prev_load_device = load_device
+                            current_device_cache_overhead = []
                             i = active_devices[current_device_i]
                             if reserve_per_device is not None:
                                 set_memory_fraction_reserve(reserve_per_device[i], i)
@@ -115,10 +117,8 @@
                             config.stc.end_deferred_load()
 
                         # Account for cache quant temporary tensors
-                        qcache_overhead = []
                         for cm in module.all_cache_modules():
                             for cl in cm.cache_layers:
-                                qcache_overhead.append(cl.get_kv_alloc_placeholder())
+                                current_device_cache_overhead.append(cl.get_kv_alloc_placeholder())
 
                         # Forward dummy state through module
                         dummy_state = module.prepare_for_device(dummy_state, params)
@@ -134,7 +134,6 @@
 
                         # Dereference extra dummy tensors
                         extra_dummy_states = None
-                        qcache_overhead = None
 
                         # We're good
                         fail = False
```

**Comment by turboderp** [comment]
I'm not sure I follow this. It only needs to account for one placeholder, since it's allocated temporarily during attention on each layer, then discarded. The layer-split loader simulates that by creating the placeholder temporarily. Keeping full FP16 K/V tensors for all layers would defeat the purpose of quantizing the cache.

Overpacking can happen in other ways, though, if the single-layer forward pass performed while loading doesn't have the same memory profile as actual inference forward passes later (if it's forced to fall back on SDPA attention for instance, there's a Gemma4-specific fix for that in `dev`), or if memory fragmentation makes a forward pass that succeeded during loading impossible later. It *shouldn't*, though, so if you have some particular case that's failing I'd like to try and debug it.

**Comment by Danielcurly** [comment]
Hi @turboderp,

You're totally right, I've dug deeper into the code and realized my assumption was off. Since `alloc()` happens during `module.load()`, the permanent VRAM for previously loaded caches is already there, so a cumulative list would definitely be 'double accounting'.

The reason I proposed that patch was because it actually fixed a 'bincount' crash I was getting during the dryruns. It turns out my `autosplit_reserve` was tuned specifically for FP16 caches. When I switched to quantized, the dryrun would crash because it didn't have enough breathing room for the dequantization overhead.

By making the placeholders cumulative, I was accidentally forcing the loader to be extremely pessimistic. That 'fake' memory pressure pushed layers onto other GPUs, which created the extra space needed to avoid the OOM during the split. So even though the logic was wrong, the extra overhead was masking the fact that quantized caches need a much larger reserve (easily 10x more than FP16) to handle the process safely.

In an 8-GPU rig like mine, the benefits of cache quantization pretty much vanish. Each GPU still needs enough free VRAM to hold the full FP16 context of a layer plus the calculation overhead used during the dequantization process itself. With the cache already split across so many GPUs, those fixed costs on every device end up eating most of the VRAM you were trying to save in the first place.

Thanks for the clarification, it helped me track down what was actually going on!
